# Generated by Django 2.2.3 on 2019-07-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('c_type', models.CharField(max_length=30)),
                ('c_desc', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('image', models.ImageField(default='', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='eregiser',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=13)),
                ('e_type', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('feedback', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('switch', models.IntegerField(default=8)),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Uregiser',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=13)),
                ('pincode', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='transection',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('c_desc', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.complain')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.eregiser')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('u_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.item')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser')),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser'),
        ),
    ]
