# Generated by Django 2.1.12 on 2019-10-16 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(choices=[('Hikvision', 'Hikvision'), ('CP Plus', 'CP Plus'), ('Zicom', 'Zicom'), ('Sony', 'Sony'), ('Samsung', 'Samsung'), ('AVtech', 'AVtech')], max_length=30)),
                ('Megapixel', models.IntegerField(default=0)),
                ('cprice', models.IntegerField(default=0)),
                ('vision', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='', max_length=30)),
                ('image', models.ImageField(default='', upload_to='image')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('p_id', models.IntegerField(default=0)),
                ('p_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='complain',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('e_id', models.IntegerField(default=0)),
                ('m_id', models.IntegerField(default=0)),
                ('u_name', models.CharField(max_length=30)),
                ('e_name', models.CharField(default='', max_length=30)),
                ('c_type', models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server'), ('Other', 'other')], max_length=30)),
                ('company', models.CharField(default='', max_length=30)),
                ('creq', models.IntegerField(default=0)),
                ('c_desc', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('contect', models.CharField(default='', max_length=10)),
                ('rstatus', models.IntegerField(default=0)),
                ('e_email', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(default='', upload_to='image')),
                ('cdate', models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 42, 180757))),
            ],
        ),
        migrations.CreateModel(
            name='eregiser',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=10)),
                ('e_type', models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server'), ('Other', 'other')], max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('feedback', models.FloatField(default=0.0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=30)),
                ('contect', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='')),
                ('company', models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('ACER', 'ACER'), ('ASUS', 'ASUS')], max_length=30)),
                ('stock', models.IntegerField(default='')),
                ('rating', models.FloatField(default=0)),
                ('crating', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('warranty', models.IntegerField(default='')),
                ('image', models.ImageField(default='', upload_to='image')),
                ('idate', models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 42, 170747))),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('i_id', models.IntegerField(default=0)),
                ('p_id', models.IntegerField(default=0)),
                ('p_name', models.CharField(max_length=30)),
                ('u_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('pay', models.CharField(max_length=128)),
                ('address', models.CharField(default='', max_length=300)),
                ('landmark', models.CharField(default='', max_length=300)),
                ('pincode', models.IntegerField(default=0)),
                ('odate', models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 42, 182086))),
                ('unumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('company', models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO')], default='', max_length=30)),
                ('u_name', models.CharField(default='', max_length=20)),
                ('switch', models.IntegerField(default=8)),
                ('contact', models.CharField(default='', max_length=13)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transection',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('c_id', models.IntegerField(default=0)),
                ('e_id', models.IntegerField(default=0)),
                ('m_id', models.IntegerField(default=0)),
                ('s_id', models.IntegerField(default=0)),
                ('u_name', models.CharField(max_length=30)),
                ('company', models.CharField(default='', max_length=30)),
                ('c_desc', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('tdate', models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 42, 182086))),
            ],
        ),
        migrations.CreateModel(
            name='Uregiser',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=13)),
                ('pincode', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', null=True, upload_to='image')),
                ('video', models.FileField(null=True, upload_to='videos', verbose_name='')),
                ('discr', models.CharField(max_length=200)),
            ],
        ),
    ]
