# Generated by Django 2.1.12 on 2019-10-16 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 56, 963846)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 56, 961327)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 56, 963846)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 3, 51, 56, 963846)),
        ),
    ]
