# Generated by Django 2.2.3 on 2019-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eregiser',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
