# Generated by Django 2.2.3 on 2019-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0003_auto_20190801_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eregiser',
            name='e_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware')], max_length=30),
        ),
    ]
