# Generated by Django 2.2.3 on 2019-08-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0004_auto_20190807_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eregiser',
            name='contect',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='uregiser',
            name='pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
