# Generated by Django 2.2.3 on 2019-08-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0005_auto_20190807_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uregiser',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
