# Generated by Django 2.2.4 on 2019-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0006_auto_20190808_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=30)),
                ('video', models.FileField(null=True, upload_to='videos', verbose_name='')),
                ('discr', models.CharField(max_length=200)),
            ],
        ),
    ]
