# Generated by Django 2.2.4 on 2019-08-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0007_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='video',
            name='v_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
