# Generated by Django 2.2.4 on 2019-08-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0008_auto_20190810_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='e_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='c_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware')], max_length=30),
        ),
    ]
