# Generated by Django 2.2.4 on 2019-08-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0009_auto_20190820_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='e_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.eregiser'),
        ),
    ]
