# Generated by Django 2.2.4 on 2019-08-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0011_auto_20190821_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser'),
        ),
    ]
