# Generated by Django 2.2.4 on 2019-08-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0013_auto_20190822_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='e_id',
            field=models.ForeignKey(db_column='e_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.eregiser'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='u_id',
            field=models.ForeignKey(db_column='u_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='corus.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.complain'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='e_id',
            field=models.ForeignKey(db_column='e_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.eregiser'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='u_id',
            field=models.ForeignKey(db_column='u_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser'),
        ),
    ]
