# Generated by Django 2.2.3 on 2019-08-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0014_auto_20190822_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transection',
            name='email',
        ),
    ]
