# Generated by Django 2.2.4 on 2019-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0015_remove_transection_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='image'),
        ),
    ]
