# Generated by Django 2.2.3 on 2019-08-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0016_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.item')),
                ('u_id', models.ForeignKey(db_column='u_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.Uregiser')),
            ],
        ),
    ]
