# Generated by Django 2.2.4 on 2019-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
