# Generated by Django 2.2.4 on 2019-09-05 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0018_cart_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Your Address', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 20, 42, 111751)),
        ),
    ]
