# Generated by Django 2.2.4 on 2019-09-05 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0019_auto_20190906_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_id',
        ),
        migrations.AddField(
            model_name='order',
            name='i_id',
            field=models.ForeignKey(db_column='i_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corus.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 35, 25, 490502)),
        ),
    ]
