# Generated by Django 2.2.4 on 2019-09-05 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0020_auto_20190906_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='i_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 40, 52, 745284)),
        ),
    ]
