# Generated by Django 2.2.4 on 2019-09-06 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0022_auto_20190906_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='u_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 3, 0, 41, 791880)),
        ),
    ]
