# Generated by Django 2.2.4 on 2019-09-07 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0026_auto_20190907_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('cod', 'Case On Deleveri'), ('net', 'Net Banking'), ('paytm', 'paytm')], default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='landmark',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 22, 49, 19, 58246)),
        ),
    ]
