# Generated by Django 2.2.4 on 2019-09-07 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0027_auto_20190907_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 23, 44, 0, 275041)),
        ),
        migrations.AddField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 23, 44, 0, 275041)),
        ),
        migrations.AddField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 23, 44, 0, 280088)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 23, 44, 0, 280088)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(max_length=128),
        ),
    ]
