# Generated by Django 2.2.4 on 2019-09-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0028_auto_20190907_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='e_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 22, 39, 11, 694052)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 22, 39, 11, 694052)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 22, 39, 11, 694052)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 22, 39, 11, 694052)),
        ),
    ]
