# Generated by Django 2.2.4 on 2019-09-11 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0030_auto_20190911_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='u_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='u_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 12, 3, 644574)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 12, 3, 644574)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 12, 3, 644574)),
        ),
        migrations.AlterField(
            model_name='server',
            name='company',
            field=models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 12, 3, 644574)),
        ),
    ]
