# Generated by Django 2.2.4 on 2019-09-11 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0031_auto_20190912_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(default=0)),
                ('company', models.CharField(choices=[('Hikvision', 'Hikvision'), ('CP Plus', 'CP Plus'), ('Zicom', 'Zicom'), ('Sony', 'Sony'), ('Samsung', 'Samsung'), ('AVtech', 'AVtech')], max_length=30)),
                ('u_name', models.CharField(default='', max_length=20)),
                ('switch', models.IntegerField(default=8)),
                ('cprice', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=13)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='c_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 32, 24, 999371)),
        ),
        migrations.AlterField(
            model_name='eregiser',
            name='e_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 32, 24, 999371)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 32, 24, 999371)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 32, 24, 999371)),
        ),
    ]
