# Generated by Django 2.2.4 on 2019-09-11 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0032_auto_20190912_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='switch',
        ),
        migrations.AddField(
            model_name='camera',
            name='vision',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 46, 1, 550000)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 46, 1, 550000)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 46, 1, 550000)),
        ),
        migrations.AlterField(
            model_name='server',
            name='contact',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 4, 46, 1, 550000)),
        ),
    ]
