# Generated by Django 2.2.4 on 2019-09-11 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0033_auto_20190912_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='Megapixel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 1, 1, 448134)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 1, 1, 448134)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 1, 1, 448134)),
        ),
        migrations.AlterField(
            model_name='server',
            name='company',
            field=models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 1, 1, 448134)),
        ),
    ]
