# Generated by Django 2.2.4 on 2019-09-11 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0034_auto_20190912_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 5, 24, 508807)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 5, 24, 493160)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 5, 24, 508807)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 5, 24, 508807)),
        ),
    ]
