# Generated by Django 2.2.4 on 2019-09-11 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0035_auto_20190912_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='u_name',
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 15, 50, 347219)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 15, 50, 347219)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 15, 50, 347219)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 5, 15, 50, 347219)),
        ),
    ]
