# Generated by Django 2.2.4 on 2019-09-12 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0038_auto_20190912_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='creq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 21, 48, 15, 231819)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 21, 48, 15, 231819)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 21, 48, 15, 231819)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 12, 21, 48, 15, 231819)),
        ),
    ]
