# Generated by Django 2.2.4 on 2019-09-12 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0040_auto_20190913_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='contect',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 0, 21, 34, 393660)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 0, 21, 34, 378038)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 0, 21, 34, 393660)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 0, 21, 34, 393660)),
        ),
    ]
