# Generated by Django 2.2.4 on 2019-09-12 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0041_auto_20190913_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='transection',
            name='m_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transection',
            name='s_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 4, 33, 8, 23871)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 4, 33, 8, 8225)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 4, 33, 8, 23871)),
        ),
        migrations.AlterField(
            model_name='server',
            name='company',
            field=models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 4, 33, 8, 23871)),
        ),
    ]
