# Generated by Django 2.2.4 on 2019-09-18 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0042_auto_20190913_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 41, 3, 355059)),
        ),
        migrations.AlterField(
            model_name='eregiser',
            name='e_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.CharField(choices=[('LG', 'LG'), ('HP', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('ACER', 'ACER'), ('ASUS', 'ASUS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 41, 3, 355059)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 41, 3, 360074)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 41, 3, 355059)),
        ),
    ]
