# Generated by Django 2.2.4 on 2019-09-18 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0043_auto_20190919_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='crating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 51, 58, 741410)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 51, 58, 741410)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 51, 58, 746417)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 3, 51, 58, 746417)),
        ),
    ]
