# Generated by Django 2.1.12 on 2019-09-24 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0044_auto_20190919_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complain',
            name='c_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server'), ('Other', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 3, 34, 8, 438780)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 3, 34, 8, 438780)),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 3, 34, 8, 438780)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 3, 34, 8, 438780)),
        ),
    ]
