# Generated by Django 2.1.12 on 2019-09-24 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0045_auto_20190925_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 9, 52, 754271)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 9, 52, 751279)),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 9, 52, 755268)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 25, 4, 9, 52, 754271)),
        ),
    ]
