# Generated by Django 2.1.12 on 2019-10-01 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0046_auto_20190925_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 3, 35, 17, 14067)),
        ),
        migrations.AlterField(
            model_name='eregiser',
            name='e_type',
            field=models.CharField(choices=[('Os', 'Os'), ('Cameras', 'Cameras'), ('Hardware', 'Hardware'), ('Server', 'Server'), ('Other', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 3, 35, 17, 14067)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 3, 35, 17, 14067)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 3, 35, 17, 14067)),
        ),
    ]
