# Generated by Django 2.1.12 on 2019-10-10 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0047_auto_20191002_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 3, 3, 35, 840722)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='contect',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='head',
            name='contect',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 3, 3, 35, 836709)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 3, 3, 35, 841720)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 3, 3, 35, 840722)),
        ),
    ]
