# Generated by Django 2.1.12 on 2019-10-10 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corus', '0048_auto_20191011_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stock',
        ),
        migrations.AlterField(
            model_name='complain',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 4, 21, 0, 801576)),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 4, 21, 0, 785955)),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 4, 21, 0, 801576)),
        ),
        migrations.AlterField(
            model_name='transection',
            name='tdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 4, 21, 0, 801576)),
        ),
    ]
